-- ---------------------------------------------------------------------------
-- Add the `ts_type` node type.
--
-- `ts_type` — TS Type Converter (Logic): reads JSON from a bound state slot,
--             generates TypeScript interface declarations, and writes them to
--             a bound output state slot.
--
-- ADD VALUE IF NOT EXISTS is idempotent and cannot run inside a txn that also
-- uses the new value, so keep this as a standalone statement.
-- ---------------------------------------------------------------------------
alter type public.tool_node_type add value if not exists 'ts_type';
