-- ---------------------------------------------------------------------------
-- Add the `number` node type.
--
-- `number` — numeric input: a slider paired with a number field, two-way bound
--            to its state slot. Config carries `min` / `max` / `step`; the
--            value is stored as a stringified number.
--
-- ADD VALUE IF NOT EXISTS is idempotent and cannot run inside a txn that also
-- uses the new value, so keep this as a standalone statement.
-- ---------------------------------------------------------------------------
alter type public.tool_node_type add value if not exists 'number';
