-- ---------------------------------------------------------------------------
-- Add the `sprite` node type.
--
-- `sprite` — Read-only sprite animation viewer over a bound state slot. The
--            value is a single sprite-sheet image (sliced into frameWidth ×
--            frameHeight cells) or an array of frame images, played as a
--            flip-book at the node's fps with idle / intro / left / right /
--            click animation tracks.
--
-- ADD VALUE IF NOT EXISTS is idempotent and cannot run inside a txn that also
-- uses the new value, so keep this as a standalone statement.
-- ---------------------------------------------------------------------------
alter type public.tool_node_type add value if not exists 'sprite';
