-- ---------------------------------------------------------------------------
-- Add the `code_input` node type.
--
-- `code_input` — two-way bound code input rendered in a Monaco editor with a
--                selectable language; raw source string is stored in the bound
--                state slot.
--
-- ADD VALUE IF NOT EXISTS is idempotent and cannot run inside a txn that also
-- uses the new value, so keep this as a standalone statement.
-- ---------------------------------------------------------------------------
alter type public.tool_node_type add value if not exists 'code_input';
