-- ---------------------------------------------------------------------------
-- Add the `select` node type.
--
-- `select` — single-choice dropdown, two-way bound to its state slot. Config
--            holds a static `options` list and an optional `optionsBinding`
--            naming a state slot whose array drives the options at runtime.
--
-- ADD VALUE IF NOT EXISTS is idempotent and cannot run inside a txn that also
-- uses the new value, so keep this as a standalone statement.
-- ---------------------------------------------------------------------------
alter type public.tool_node_type add value if not exists 'select';
